export enum ExpenseCategory {
  MATERIAL_PURCHASE = 'Achat matière',
  WORKER_SALARIES = 'Salaires',
  RENT = 'Loyer',
  ELECTRICITY = 'Électricité',
  WATER = 'Eau',
  GAS = 'Gaz',
  INTERNET_PHONE = 'Internet / Téléphone',
  MAINTENANCE = 'Maintenance',
  REPAIR = 'Réparation',
  TRANSPORT = 'Transport',
  FUEL = 'Carburant',
  SUPPLIES = 'Fournitures',
  CLEANING = 'Nettoyage',
  OTHER = 'Autre',
  FABRIC_PURCHASE = 'Achat tissu',
  THREADS_ACCESSORIES = 'Fils et accessoires',
  UTILITIES = 'Charges utilitaires',
  MACHINE_MAINTENANCE = 'Maintenance machines',
}
