import { palette } from "../content";

export type Lang = "ar" | "fr";
export type Bilingual = { ar: string; fr: string };

export const analyticsText: Record<Lang, any> = {
  ar: {
    currency: "د.ج",
    breadcrumbHome: "الرئيسية",
    breadcrumb: "تحليل البيانات والتقارير",
    title: "تحليل البيانات والتقارير",
    subtitle: "لوحة تحليل ذكية تساعد على فهم أداء الورشة واتخاذ قرارات أفضل بناءً على المبيعات، الإنتاج والمصاريف",
    summary: {
      sales: "إجمالي المبيعات", salesHelp: "قيمة المبيعات خلال الفترة المحددة",
      profits: "إجمالي الأرباح", profitsHelp: "الربح بعد خصم المصاريف",
      expenses: "إجمالي المصاريف", expensesHelp: "مجموع النفقات المسجلة",
      delayed: "الطلبات المتأخرة", delayedHelp: "طلبيات تجاوزت تاريخ التسليم",
      topWorker: "أكثر عامل إنتاجاً", topWorkerHelp: "العامل الأعلى إنتاجية",
      topProduct: "أكثر منتج مبيعاً", topProductHelp: "المنتج الأكثر طلباً",
    },
    tabs: {
      overview: "نظرة عامة",
      salesProfits: "المبيعات والأرباح",
      workersProd: "العمال والإنتاج",
      stockMat: "المخزون والمواد",
      orders: "الطلبيات",
      detailed: "التقارير المفصلة",
    },
    actions: {
      dateRange: "اليوم / الأسبوع / الشهر...",
      reportType: "نوع التقرير",
      product: "المنتج",
      worker: "العامل",
      customer: "الزبون",
      createReport: "إنشاء تقرير",
      exportPdf: "تصدير PDF",
      exportExcel: "تصدير Excel",
      print: "طباعة",
      allDates: "كل الفترات",
      thisMonth: "هذا الشهر",
      thisYear: "هذه السنة",
    },
    charts: {
      salesProfits: "نظرة عامة على المبيعات والأرباح",
      sales: "المبيعات",
      profits: "الأرباح",
      expensesRev: "مقارنة المبيعات والمصاريف",
      netProfit: "الربح الصافي",
      topProducts: "أفضل المنتجات مبيعاً",
      topWorkers: "أكثر العمال إنتاجاً",
      topMaterials: "المواد الأكثر استهلاكاً",
      delayedOrders: "الطلبيات المتأخرة",
      activityTrend: "الأشهر الأكثر نشاطاً",
      salesVsProd: "مقارنة بين الإنتاج والمبيعات",
      topCustomers: "أكثر الزبائن تعاملاً",
      profitability: "تحليل الربحية",
    },
    insights: {
      title: "الاستنتاجات والتنبيهات",
      quickInsights: "استنتاجات سريعة",
      alerts: "تنبيهات",
      actions: "اقتراحات عملية",
    },
    modals: {
      report: {
        title: "إنشاء تقرير جديد",
        type: "نوع التقرير",
        period: "الفترة الزمنية",
        section: "حسب القسم",
        worker: "العامل",
        customer: "الزبون",
        product: "المنتج",
        display: "طريقة العرض",
        format: "تنسيق التصدير",
        save: "إنشاء التقرير",
        preview: "معاينة",
        cancel: "إلغاء",
        types: {
          sales: "تقرير المبيعات",
          profits: "تقرير الأرباح",
          expenses: "تقرير المصاريف",
          workers: "تقرير العمال",
          stock: "تقرير المخزون",
          orders: "تقرير الطلبيات",
          full: "تقرير شامل",
        },
        displays: {
          summary: "ملخص",
          detailed: "مفصل",
          charts: "رسوم بيانية",
          table: "جدول",
        }
      }
    }
  },
  fr: {
    currency: "DA",
    breadcrumbHome: "Accueil",
    breadcrumb: "Analyses et Rapports",
    title: "Analyses et Rapports",
    subtitle: "Tableau de bord intelligent pour comprendre les performances et prendre de meilleures décisions",
    summary: {
      sales: "Total des ventes", salesHelp: "Valeur des ventes sur la période",
      profits: "Bénéfice total", profitsHelp: "Bénéfice après dépenses",
      expenses: "Total dépenses", expensesHelp: "Somme des dépenses enregistrées",
      delayed: "Commandes en retard", delayedHelp: "Commandes dépassant le délai",
      topWorker: "Meilleur employé", topWorkerHelp: "Employé le plus productif",
      topProduct: "Top produit", topProductHelp: "Produit le plus vendu",
    },
    tabs: {
      overview: "Vue d'ensemble",
      salesProfits: "Ventes & Bénéfices",
      workersProd: "Ouvriers & Production",
      stockMat: "Stock & Matériaux",
      orders: "Commandes",
      detailed: "Rapports détaillés",
    },
    actions: {
      dateRange: "Aujourd'hui / Semaine / Mois...",
      reportType: "Type de rapport",
      product: "Produit",
      worker: "Ouvrier",
      customer: "Client",
      createReport: "Créer un rapport",
      exportPdf: "Export PDF",
      exportExcel: "Export Excel",
      print: "Imprimer",
      allDates: "Toutes périodes",
      thisMonth: "Ce mois",
      thisYear: "Cette année",
    },
    charts: {
      salesProfits: "Aperçu des Ventes et Bénéfices",
      sales: "Ventes",
      profits: "Bénéfices",
      expensesRev: "Ventes vs Dépenses",
      netProfit: "Bénéfice Net",
      topProducts: "Meilleurs produits",
      topWorkers: "Ouvriers les plus productifs",
      topMaterials: "Matières les plus consommées",
      delayedOrders: "Commandes en retard",
      activityTrend: "Mois les plus actifs",
      salesVsProd: "Production vs Ventes",
      topCustomers: "Meilleurs clients",
      profitability: "Analyse de rentabilité",
    },
    insights: {
      title: "Insights et Alertes",
      quickInsights: "Insights rapides",
      alerts: "Alertes",
      actions: "Actions suggérées",
    },
    modals: {
      report: {
        title: "Créer un nouveau rapport",
        type: "Type",
        period: "Période",
        section: "Section",
        worker: "Ouvrier",
        customer: "Client",
        product: "Produit",
        display: "Affichage",
        format: "Format d'export",
        save: "Créer le rapport",
        preview: "Aperçu",
        cancel: "Annuler",
        types: {
          sales: "Rapport des ventes",
          profits: "Rapport des bénéfices",
          expenses: "Rapport des dépenses",
          workers: "Rapport des ouvriers",
          stock: "Rapport de stock",
          orders: "Rapport des commandes",
          full: "Rapport complet",
        },
        displays: {
          summary: "Résumé",
          detailed: "Détaillé",
          charts: "Graphiques",
          table: "Tableau",
        }
      }
    }
  }
};

export { palette };
