export const INITIAL_SCHEMA_VERSION = 1;
export const STARTUP_PERFORMANCE_SCHEMA_VERSION = 2;
export const CURRENT_SCHEMA_VERSION = 3;
export const INITIAL_BASELINE_MIGRATION = 'InitialSchemaBaseline1788102000000';
